# Communication Breakdown

Now you're take a closer look at how the client and server communicated
with each other.

![Loopback](https://files.realpython.com/media/sockets-loopback-interface.44fa30c53c70.jpg)

When using the loopback interface (IPv4 address `127.0.0.1` or IPv6 address `::1`),
data never leaves the host or touches the external network.
In the diagram above, the loopback interface is contained inside the host.
This represents the internal nature of the loopback interface
and shows that connections and data that transit it are local to the host.
This is why you’ll also hear the loopback interface
and IP address `127.0.0.1` or `::1` referred to as “localhost.”

> loopback IF を用いるときは
> データはどこのホストにも送信されず、また外部のネットワークにも送信されない
> 上の表を見ると ループバック IF はホストの中に存在している
> これは Loopback IF の内部的な性質を表している
> それを通過する接続とデータはホストのローカルであることを示している
> これが LoopbackIf を聞く理由であり
> IP address 127.0.0.1 / ::1 が localhost と呼ばれる理由

Applications use the loopback interface to communicate with other processes
running on the host and for security and isolation from the external network.
Because it’s internal and accessible only from within the host, it’s not exposed.

> apps は〜のため Loopback IF を利用する
> ホスト上で実行している他のプロセスと通信をするため
> 外部のネットワークからの独立性や、セキュリティのため
> なぜなら Loopback IF は(ローカルにのみ利用可能)内部的で
> 同一ホスト上に存在するときにのみ利用できるから
> 外部にさらされてないからね

You can see this in action
if you have an application server that uses its own private database.
If it’s not a database used by other servers,
it’s probably configured to listen for connections on the loopback interface only.
If this is the case, other hosts on the network can’t connect to it.

> LoopbackIF が実行中なのを確認することができる
> 例えば 自身の Private な DB を使ったアプリケーションサーバーを持っているとき
> もし他のサーバーが利用していないサーバーであった場合
> 通常は Loopback IF 空のみコネクションを Listen しているでしょう
> もしそうであれば (Loopback IF を利用しているので) 同一ネットワーク上の
> 他のホストからは接続は出来ません

When you use an IP address other than 127.0.0.1 or ::1 in your applications,
it’s probably bound to an Ethernet interface that’s connected to an external
network. This is your gateway to other hosts outside of your “localhost” kingdom:

> loopback アドレス以外の IP を利用すれば
> 外部のネットワークと接続ができる Ethernet IF とバウンドできます
> 自分の環境の Loopback IF の外とのゲートウェイになります

![External Interface](https://files.realpython.com/media/sockets-ethernet-interface.aac312541af5.jpg)

## Handling Multiple Connections

The echo server definitely has its limitations.
The biggest one is that it serves only one client and then exits.
The echo client has this limitation too, but there’s an additional problem.
When the client uses `s.recv()`, it’s possible that it will return only one byte,
b'H' from b'Hello, world':

> echo server は明確な制限があります
> 最も大きな制約とは 一つのクライアントとしか通信が出来ないというもの
> Echo client も制限はあるが、ただ別の問題です
> client が s.recv() を使ったとき、返却できるのたった 1 倍とだけです
> Hello, world の H だけ

```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    s.sendall(b"Hello, world")
    data = s.recv(1024) # bufsize

print(f"Received {data!r}")
```

The `bufsize` argument of 1024 used above is the `maximum` amount of data
to be received at once. It doesn’t mean that `.recv()` will return 1024 bytes.

> bufsize の 1024 ってのは 一度に受け取れる data のサイズの最大値のこと
> .recv() は返却できるバイト数のことではない

The `.send()` method also behaves this way. It returns the number of bytes sent,
which may be less than the size of the data passed in.
You’re responsible for checking this and calling `.send()`
as many times as needed to send all of the data:

> .send() も同様の振る舞いをする
> 送信された Bytes 数を返却する 入ってきたバイト数がこれより大きければ
> Bytes を損失する可能性があります
> すべての送信する必要があれば .send() が必要な回数だけ呼ばれることを
> 確認する必要がありますね

"Applications are responsible for checking that all data has been sent;
if only some of the data was transmitted, the application needs to attempt
delivery of the remaining data."

> アプリは〜に責任を持っている ：すべてのデータが送信されたことを
> あるデータが送信されたとき、アプリは残りのデータを配送することが必要

In the example above, you avoided having to do this by using `.sendall()`:
"Unlike send(), this method continues to send data from bytes
until either all data has been sent or an error occurs.
None is returned on success."

> 上の例では、すべてのデータの送信を保証するには .send all() を使えば OK
> send() とは違い .sendall() は でーたを送信し続けます
> エラーが発生する or データが送信できるまでずっと
> None が返却される、すなわち成功

You have two problems at this point:

- How do you handle multiple connections concurrently?
- You need to call .send() and .recv() until all data is sent or received.

> ここには 2 つの問題点がある
> 並列にコネクションを扱うにはどうすれば
> .send(), .recv() を呼ぶ必要がある すべてのデータを送信 or 受信できるまで

What can you do? There are many approaches to concurrency.
A popular approach is to use Asynchronous I/O. asyncio was introduced
into the standard library in Python 3.4.
The traditional choice is to use threads.

> どうする 並列については多くのアプローチがある
> 一般的なのは 非同期 I/O がを使うこと
> asyncio は python3.4 で STL になっている

The trouble with concurrency is it’s hard to get right.
There are many subtleties to consider and guard against.
All it takes is for one of these to manifest itself
and your application may suddenly fail in not-so-subtle ways.

> 並列処理のトラブルを解消するのはとても大変
> 多くの微妙なものがある これを考えたり対策するのは
